package com.cubolabs.bibliaofflinearc.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PALAVRA.
*/
public class PalavraDao extends AbstractDao<Palavra, Long> {

    public static final String TABLENAME = "PALAVRA";

    /**
     * Properties of entity Palavra.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id_palavra");
        public final static Property Id_livro = new Property(1, long.class, "id_livro", false, "ID_LIVRO");
        public final static Property Capitulo = new Property(2, short.class, "capitulo", false, "CAPITULO");
        public final static Property Versiculo = new Property(3, short.class, "versiculo", false, "VERSICULO");
        public final static Property Texto = new Property(4, String.class, "texto", false, "TEXTO");
    };

    private DaoSession daoSession;

    private Query<Palavra> livro_PalavrasQuery;

    public PalavraDao(DaoConfig config) {
        super(config);
    }
    
    public PalavraDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PALAVRA' (" + //
                "'id_palavra' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_LIVRO' INTEGER NOT NULL ," + // 1: id_livro
                "'CAPITULO' INTEGER NOT NULL ," + // 2: capitulo
                "'VERSICULO' INTEGER NOT NULL ," + // 3: versiculo
                "'TEXTO' TEXT);"); // 4: texto
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PALAVRA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Palavra entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getId_livro());
        stmt.bindLong(3, entity.getCapitulo());
        stmt.bindLong(4, entity.getVersiculo());
 
        String texto = entity.getTexto();
        if (texto != null) {
            stmt.bindString(5, texto);
        }
    }

    @Override
    protected void attachEntity(Palavra entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Palavra readEntity(Cursor cursor, int offset) {
        Palavra entity = new Palavra( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // id_livro
            cursor.getShort(offset + 2), // capitulo
            cursor.getShort(offset + 3), // versiculo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // texto
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Palavra entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_livro(cursor.getLong(offset + 1));
        entity.setCapitulo(cursor.getShort(offset + 2));
        entity.setVersiculo(cursor.getShort(offset + 3));
        entity.setTexto(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Palavra entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Palavra entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "palavras" to-many relationship of Livro. */
    public List<Palavra> _queryLivro_Palavras(long id_livro) {
        synchronized (this) {
            if (livro_PalavrasQuery == null) {
                QueryBuilder<Palavra> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id_livro.eq(null));
                queryBuilder.orderRaw("ID_LIVRO ASC,CAPITULO ASC,VERSICULO ASC");
                livro_PalavrasQuery = queryBuilder.build();
            }
        }
        Query<Palavra> query = livro_PalavrasQuery.forCurrentThread();
        query.setParameter(0, id_livro);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLivroDao().getAllColumns());
            builder.append(" FROM PALAVRA T");
            builder.append(" LEFT JOIN LIVRO T0 ON T.'ID_LIVRO'=T0.'id_livro'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Palavra loadCurrentDeep(Cursor cursor, boolean lock) {
        Palavra entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Livro livro = loadCurrentOther(daoSession.getLivroDao(), cursor, offset);
         if(livro != null) {
            entity.setLivro(livro);
        }

        return entity;    
    }

    public Palavra loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Palavra> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Palavra> list = new ArrayList<Palavra>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Palavra> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Palavra> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
