package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table books.
 */
public class Book {

    private Long ordering;
    private String name;
    private String abbreviation;
    private String testament;

    public Book() {
    }

    public Book(Long ordering) {
        this.ordering = ordering;
    }

    public Book(Long ordering, String name, String abbreviation, String testament) {
        this.ordering = ordering;
        this.name = name;
        this.abbreviation = abbreviation;
        this.testament = testament;
    }

    public Long getOrdering() {
        return ordering;
    }

    public void setOrdering(Long ordering) {
        this.ordering = ordering;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getTestament() {
        return testament;
    }

    public void setTestament(String testament) {
        this.testament = testament;
    }

}
