package com.cubolabs.bibliaofflinearc;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cubolabs.bibliaofflinearc.Testamento;
import com.cubolabs.bibliaofflinearc.Livro;
import com.cubolabs.bibliaofflinearc.Palavra;

import com.cubolabs.bibliaofflinearc.TestamentoDao;
import com.cubolabs.bibliaofflinearc.LivroDao;
import com.cubolabs.bibliaofflinearc.PalavraDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testamentoDaoConfig;
    private final DaoConfig livroDaoConfig;
    private final DaoConfig palavraDaoConfig;

    private final TestamentoDao testamentoDao;
    private final LivroDao livroDao;
    private final PalavraDao palavraDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testamentoDaoConfig = daoConfigMap.get(TestamentoDao.class).clone();
        testamentoDaoConfig.initIdentityScope(type);

        livroDaoConfig = daoConfigMap.get(LivroDao.class).clone();
        livroDaoConfig.initIdentityScope(type);

        palavraDaoConfig = daoConfigMap.get(PalavraDao.class).clone();
        palavraDaoConfig.initIdentityScope(type);

        testamentoDao = new TestamentoDao(testamentoDaoConfig, this);
        livroDao = new LivroDao(livroDaoConfig, this);
        palavraDao = new PalavraDao(palavraDaoConfig, this);

        registerDao(Testamento.class, testamentoDao);
        registerDao(Livro.class, livroDao);
        registerDao(Palavra.class, palavraDao);
    }
    
    public void clear() {
        testamentoDaoConfig.getIdentityScope().clear();
        livroDaoConfig.getIdentityScope().clear();
        palavraDaoConfig.getIdentityScope().clear();
    }

    public TestamentoDao getTestamentoDao() {
        return testamentoDao;
    }

    public LivroDao getLivroDao() {
        return livroDao;
    }

    public PalavraDao getPalavraDao() {
        return palavraDao;
    }

}
